var productsCatalog = [
  {
    id: "el01",
    name: "Костюм брючный",
    size: "42",
    img: "img/imgDress/IMG_9816.jpg",
  },
  {
    id: "el02",
    name: "Платье мята",
    size: "46,48",
    img: "img/imgDress/IMG_9817.jpg",
  },
  {
    id: "el03",
    name: "Платье",
    size: "46,48",
    img: "img/imgDress/IMG_9822.jpg",
  },
  {
    id: "el04",
    name: "Комбез",
    size: "42,44",
    img: "img/imgDress/IMG_9823.jpg",
  },
  {
    id: "el05",
    name: "Платье горох",
    size: "42-48",
    img: "img/imgDress/IMG_9824.jpg",
  },
  {
    id: "el06",
    name: "Платье",
    size: "42,46",
    img: "img/imgDress/IMG_9832.jpg",
  },
  {
    id: "el07",
    name: "Платье",
    size: "42-48",
    img: "img/imgDress/IMG_9835.jpg",
  },
  {
    id: "el08",
    name: "Платье бежевое",
    size: "42,44",
    img: "img/imgDress/IMG_9838.jpg",
  },
  {
    id: "el09",
    name: "Комбез горох",
    size: "42-48",
    img: "img/imgDress/IMG_9840.jpg",
  },
  { id: "el10", name: "...", size: "42,44", img: "img/imgDress/IMG_9843.jpg" },
  { id: "el11", name: "...", size: "42", img: "img/imgDress/IMG_9845.jpg" },
  {
    id: "el12",
    name: "Платье",
    size: "42-46",
    img: "img/imgDress/IMG_9847.jpg",
  },
  {
    id: "el13",
    name: "Костюм фуксия",
    size: "42",
    img: "img/imgDress/IMG_9849.jpg",
  },
  {
    id: "el14",
    name: "Костюм клетка",
    size: "42",
    img: "img/imgDress/IMG_9851.jpg",
  },
  {
    id: "el15",
    name: "Блуза",
    size: "42,46",
    img: "img/imgDress/IMG_9857.jpg",
  },
  {
    id: "el16",
    name: "Блуза пудра",
    size: "48,52",
    img: "img/imgDress/IMG_9859.jpg",
  },
  {
    id: "el17",
    name: "Футболка красная",
    size: "42",
    img: "img/imgDress/IMG_9869.jpg",
  },
  {
    id: "el18",
    name: "Футболка",
    size: "50",
    img: "img/imgDress/IMG_9871.jpg",
  },
  {
    id: "el19",
    name: "Сарафан полоска",
    size: "42,44,48",
    img: "img/imgDress/IMG_9879.jpg",
  },
  {
    id: "el20",
    name: "Саафан",
    size: "42-48",
    img: "img/imgDress/IMG_9881.jpg",
  },
  {
    id: "el21",
    name: "Платье горох",
    size: "48",
    img: "img/imgDress/IMG_9882.jpg",
  },
  {
    id: "el22",
    name: "Платье сирень",
    size: "48",
    img: "img/imgDress/IMG_9883.jpg",
  },
  {
    id: "el23",
    name: "Костюм",
    size: "46,48",
    img: "img/imgDress/IMG_9885.jpg",
  },
  {
    id: "el24",
    name: "Платье синие",
    size: "42,44,46",
    img: "img/imgDress/IMG_9886.jpg",
  },
  {
    id: "el25",
    name: "Платье",
    size: "46,48",
    img: "img/imgDress/IMG_9887.jpg",
  },
  {
    id: "el26",
    name: "Платье горох",
    size: "42-48",
    img: "img/imgDress/IMG_9888.jpg",
  },
  {
    id: "el27",
    name: "Платье с бабочкой",
    size: "46",
    img: "img/imgDress/IMG_9889.jpg",
  },
  {
    id: "el28",
    name: "Платье лен",
    size: "44,46",
    img: "img/imgDress/IMG_9890.jpg",
  },
  {
    id: "el29",
    name: "Платье шифон",
    size: "42-48",
    img: "img/imgDress/IMG_9891.jpg",
  },
  {
    id: "el30",
    name: "Платье горчица",
    size: "42-48",
    img: "img/imgDress/IMG_9892.jpg",
  },
  {
    id: "el31",
    name: "Платье-пиджак",
    size: "46",
    img: "img/imgDress/IMG_9893.jpg",
  },
  {
    id: "el32",
    name: "Платье",
    size: "46,48",
    img: "img/imgDress/IMG_9895.jpg",
  },
  {
    id: "el33",
    name: "Платье-пиджак",
    size: "44,48",
    img: "img/imgDress/IMG_9896.jpg",
  },
  {
    id: "el34",
    name: "Платье",
    size: "42-48",
    img: "img/imgDress/IMG_9897.jpg",
  },
  { id: "el35", name: "Комбез", size: "44", img: "img/imgDress/IMG_9900.jpg" },
  {
    id: "el36",
    name: "Брючный костюм",
    size: "46,48",
    img: "img/imgDress/IMG_9901.jpg",
  },
];
